const state={data:null,hiddenRoutes:new Set(),scale:1,tx:0,ty:0,drag:null};const svg=document.getElementById('map'),vp=document.getElementById('viewport'),routesLayer=document.getElementById('routesLayer'),stationsLayer=document.getElementById('stationsLayer'),labelsLayer=document.getElementById('labelsLayer'),empty=document.getElementById('emptyState'),popup=document.getElementById('stationPopup');const NS='http://www.w3.org/2000/svg';
function el(n,a={}){const e=document.createElementNS(NS,n);for(const[k,v]of Object.entries(a))e.setAttribute(k,v);return e}function color(v){if(typeof v==='number')return '#'+v.toString(16).padStart(6,'0');if(typeof v==='string'){if(v.startsWith('#'))return v;const n=Number(v);if(Number.isFinite(n))return '#'+n.toString(16).padStart(6,'0')}return '#607d8b'}
function payload(j){return j&&j.data?j.data:j}function routeStations(r){return r.stations||r.routeStations||r.platforms||[]}function stationId(s){return s.id||s.hexId||s.stationId||''}function stationName(s){return s.name||s.stationName||s.id||'Station'}function sx(s){return Number(s.x??s.position?.x??0)}function sz(s){return Number(s.z??s.position?.z??0)}
async function load(){try{const r=await fetch('data/network.json',{cache:'no-store'});if(!r.ok)throw Error('No snapshot');state.data=payload(await r.json());document.getElementById('statusDot').classList.add('ok');document.getElementById('snapshotStatus').textContent='Public snapshot loaded';const t=state.data.exportedAt||state.data.generatedAt;document.getElementById('snapshotTime').textContent=t?new Date(t).toLocaleString():'';render()}catch(e){document.getElementById('statusDot').classList.add('bad');document.getElementById('snapshotStatus').textContent='No network snapshot';empty.hidden=false}}
function normalize(){const routes=state.data.routes||[];const stationMap=new Map;for(const s of state.data.stations||[])stationMap.set(stationId(s),{...s,x:sx(s),z:sz(s)});for(const r of routes)for(const s of routeStations(r)){const id=stationId(s);if(!stationMap.has(id))stationMap.set(id,{...s,x:sx(s),z:sz(s),name:stationName(s)})}return{routes,stations:[...stationMap.values()]}}
function render(){empty.hidden=true;routesLayer.innerHTML=stationsLayer.innerHTML=labelsLayer.innerHTML='';const{routes,stations}=normalize();for(const r of routes){const id=r.id||r.hexId||r.name;if(state.hiddenRoutes.has(id))continue;const pts=routeStations(r).map(s=>`${sx(s)},${sz(s)}`).join(' ');if(!pts)continue;routesLayer.appendChild(el('polyline',{points:pts,class:'route-line',stroke:color(r.color), 'stroke-width':6}))}for(const s of stations){const c=el('circle',{cx:s.x,cy:s.z,r:6,class:'station'});c.addEventListener('click',ev=>showStation(s,ev));stationsLayer.appendChild(c);const t=el('text',{x:s.x+9,y:s.z-9,class:'station-label'});t.textContent=stationName(s);labelsLayer.appendChild(t)}buildRoutes(routes);fit()}
function buildRoutes(routes){const box=document.getElementById('routeList');box.innerHTML='';for(const r of routes){const id=r.id||r.hexId||r.name;const row=document.createElement('label');row.className='route-item';row.innerHTML=`<input type="checkbox" ${state.hiddenRoutes.has(id)?'':'checked'}><span class="swatch" style="background:${color(r.color)}"></span><span class="route-name">${r.name||r.routeNumber||id}</span>`;row.querySelector('input').addEventListener('change',e=>{e.target.checked?state.hiddenRoutes.delete(id):state.hiddenRoutes.add(id);renderNoFit()});box.appendChild(row)}}
function renderNoFit(){const old={scale:state.scale,tx:state.tx,ty:state.ty};render();Object.assign(state,old);applyTransform()}
function fit(){const{stations}=normalize();if(!stations.length)return;const xs=stations.map(s=>s.x),zs=stations.map(s=>s.z),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),w=svg.clientWidth,h=svg.clientHeight,p=80;state.scale=Math.min((w-p*2)/Math.max(1,maxX-minX),(h-p*2)/Math.max(1,maxZ-minZ));state.tx=w/2-state.scale*(minX+maxX)/2;state.ty=h/2-state.scale*(minZ+maxZ)/2;applyTransform()}
function applyTransform(){vp.setAttribute('transform',`translate(${state.tx} ${state.ty}) scale(${state.scale})`)}function zoom(f,cx=svg.clientWidth/2,cy=svg.clientHeight/2){state.tx=cx-(cx-state.tx)*f;state.ty=cy-(cy-state.ty)*f;state.scale*=f;applyTransform()}
svg.addEventListener('wheel',e=>{e.preventDefault();const r=svg.getBoundingClientRect();zoom(e.deltaY<0?1.15:.87,e.clientX-r.left,e.clientY-r.top)},{passive:false});svg.addEventListener('pointerdown',e=>{state.drag={x:e.clientX,y:e.clientY,tx:state.tx,ty:state.ty};svg.setPointerCapture(e.pointerId);svg.classList.add('dragging')});svg.addEventListener('pointermove',e=>{if(!state.drag)return;state.tx=state.drag.tx+e.clientX-state.drag.x;state.ty=state.drag.ty+e.clientY-state.drag.y;applyTransform()});svg.addEventListener('pointerup',()=>{state.drag=null;svg.classList.remove('dragging')});
document.getElementById('zoomIn').onclick=()=>zoom(1.2);document.getElementById('zoomOut').onclick=()=>zoom(.83);document.getElementById('fitMap').onclick=fit;document.getElementById('toggleAll').onclick=()=>{const rs=normalize().routes;if(state.hiddenRoutes.size){state.hiddenRoutes.clear()}else rs.forEach(r=>state.hiddenRoutes.add(r.id||r.hexId||r.name));document.getElementById('toggleAll').textContent=state.hiddenRoutes.size?'Show all':'Hide all';renderNoFit()};
function showStation(s,e){popup.hidden=false;popup.style.left=Math.min(svg.clientWidth-290,e.clientX-svg.getBoundingClientRect().left+12)+'px';popup.style.top=Math.min(svg.clientHeight-130,e.clientY-svg.getBoundingClientRect().top+12)+'px';popup.innerHTML=`<h3>${stationName(s)}</h3><p>X ${Math.round(s.x)} · Z ${Math.round(s.z)}</p><p>ID: ${stationId(s)}</p>`}document.addEventListener('click',e=>{if(!e.target.closest('.station')&&!e.target.closest('.station-popup'))popup.hidden=true});
const search=document.getElementById('stationSearch'),results=document.getElementById('searchResults');search.addEventListener('input',()=>{if(!state.data)return;const q=search.value.trim().toLowerCase();results.innerHTML='';if(!q){results.classList.remove('show');return}for(const s of normalize().stations.filter(s=>stationName(s).toLowerCase().includes(q)).slice(0,8)){const d=document.createElement('div');d.className='search-result';d.textContent=stationName(s);d.onclick=()=>{const x=s.x*state.scale+state.tx,y=s.z*state.scale+state.ty;state.tx+=svg.clientWidth/2-x;state.ty+=svg.clientHeight/2-y;applyTransform();results.classList.remove('show');search.value=stationName(s)};results.appendChild(d)}results.classList.toggle('show',results.childElementCount>0)});load();
