// ==UserScript==
// @name         MTR Map Tools - Folityn Schematic v6.2
// @namespace    https://github.com/peachemce/mtr-map-tools
// @version      6.2.0
// @description  Train-first corridor renderer: shared physical rail corridors, Centralny rail throat, selective one-way stops, geography-first light rail.
// @match        http://localhost:8888/*
// @run-at       document-idle
// @grant        none
// @sandbox      raw
// @updateURL    https://raw.githubusercontent.com/peachemce/mtr-map-tools/main/connector-reroll.user.js
// @downloadURL  https://raw.githubusercontent.com/peachemce/mtr-map-tools/main/connector-reroll.user.js
// ==/UserScript==

(() => {
'use strict';
const NS='http://www.w3.org/2000/svg';
const KEY='folityn-v62-';
const CFG={spacing:72,laneGap:6.4,pad:180,curve:18,snapStep:Math.PI/8,straightTol:.11,shortcutRatio:1.34,shortcutPerp:.16,shortcutHops:6,throatHalf:70};
const state={dark:localStorage.getItem(KEY+'dark')!=='0',labels:localStorage.getItem(KEY+'labels')||'key',visible:new Set(JSON.parse(localStorage.getItem(KEY+'modes')||'["light_rail","rail","high_speed"]')),wrapper:null,overlay:null,svg:null,layers:null,model:null,view:null,fitView:null,drag:null,panel:null,selectedRoute:null};
const norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLocaleLowerCase();
const pairKey=(a,b)=>a<b?`${a}|${b}`:`${b}|${a}`;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(b.x-a.x,b.y-a.y);
const colorHex=n=>`#${((Number(n)>>>0)&0xffffff).toString(16).padStart(6,'0')}`;
const median=v=>{if(!v.length)return 1;const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function modeOf(type){const t=String(type||'').toLowerCase().replace(/[\s-]+/g,'_');if(t==='train_light_rail')return'light_rail';if(t==='train_normal')return'rail';if(t==='train_high_speed')return'high_speed';return null}
const modeLabel=m=>({light_rail:'Light Rail',rail:'Rail',high_speed:'High Speed'})[m]||m;
const modeOrder=m=>({high_speed:0,rail:1,light_rail:2})[m]??9;
function svgEl(tag,attrs={}){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));return e}
async function waitForMap(){for(;;){const w=document.querySelector('app-map .wrapper, .wrapper');if(w?.querySelector('canvas'))return w;await new Promise(r=>setTimeout(r,250))}}
async function loadNetwork(){const r=await fetch('/mtr/api/map/stations-and-routes?dimension=0',{cache:'no-store'});if(!r.ok)throw new Error(`MTR network request failed (${r.status})`);const j=await r.json();return j?.data??j}
function pointSegDistance(p,a,b){const vx=b.x-a.x,vy=b.y-a.y,wx=p.x-a.x,wy=p.y-a.y,vv=vx*vx+vy*vy;if(!vv)return dist(p,a);const t=clamp((wx*vx+wy*vy)/vv,0,1);return Math.hypot(p.x-(a.x+vx*t),p.y-(a.y+vy*t))}
function projectToSeg(p,a,b){const vx=b.x-a.x,vy=b.y-a.y,vv=vx*vx+vy*vy;if(!vv)return{...a};const t=clamp(((p.x-a.x)*vx+(p.y-a.y)*vy)/vv,0,1);return{x:a.x+vx*t,y:a.y+vy*t}}
function snapDir(a,b){const dx=b.x-a.x,dy=b.y-a.y,L=Math.hypot(dx,dy);if(L<.001)return{...b};const ang=Math.atan2(dy,dx),sa=Math.round(ang/CFG.snapStep)*CFG.snapStep;return{x:a.x+Math.cos(sa)*L,y:a.y+Math.sin(sa)*L}}
function roundedPath(points,r=CFG.curve){if(points.length<2)return'';if(points.length===2)return`M ${points[0].x} ${points[0].y} L ${points[1].x} ${points[1].y}`;let d=`M ${points[0].x} ${points[0].y}`;for(let i=1;i<points.length-1;i++){const a=points[i-1],b=points[i],c=points[i+1],l1=dist(a,b),l2=dist(b,c);if(l1<.01||l2<.01)continue;const rr=Math.min(r,l1*.33,l2*.33),u1={x:(b.x-a.x)/l1,y:(b.y-a.y)/l1},u2={x:(c.x-b.x)/l2,y:(c.y-b.y)/l2},pin={x:b.x-u1.x*rr,y:b.y-u1.y*rr},pout={x:b.x+u2.x*rr,y:b.y+u2.y*rr};d+=` L ${pin.x} ${pin.y} Q ${b.x} ${b.y} ${pout.x} ${pout.y}`}const z=points.at(-1);return d+` L ${z.x} ${z.y}`}
function offsetPolyline(points,off){if(Math.abs(off)<.001||points.length<2)return points.map(p=>({...p}));const normals=[];for(let i=1;i<points.length;i++){const dx=points[i].x-points[i-1].x,dy=points[i].y-points[i-1].y,l=Math.max(.001,Math.hypot(dx,dy));normals.push({x:-dy/l,y:dx/l})}return points.map((p,i)=>{let n;if(i===0)n=normals[0];else if(i===points.length-1)n=normals.at(-1);else{const x=normals[i-1].x+normals[i].x,y=normals[i-1].y+normals[i].y,l=Math.hypot(x,y);n=l<.001?normals[i]:{x:x/l,y:y/l}}return{x:p.x+n.x*off,y:p.y+n.y*off}})}

function buildModel(data){
  const visual=new Map([
    ['folityn wity',{id:'hub:wity',name:'Wity',hub:'wity'}],['wity pkm',{id:'hub:wity',name:'Wity',hub:'wity'}],
    ['folityn jamnikowsko',{id:'hub:jamnikowsko',name:'Folityn Jamnikowsko',hub:'jamnikowsko'}],['jamnikowsko pkm',{id:'hub:jamnikowsko',name:'Folityn Jamnikowsko',hub:'jamnikowsko'}]
  ]);
  const rawToLogical=new Map(),stationMeta=new Map(),rawStation=new Map();
  const logicalFor=s=>{const n=norm(s.name);if(visual.has(n))return visual.get(n);return{id:`name:${n||s.id}`,name:String(s.name||s.id),hub:n==='folityn centralny'?'central':null}};
  for(const s of data.stations||[]){rawStation.set(s.id,s);const d=logicalFor(s);rawToLogical.set(s.id,d.id);if(!stationMeta.has(d.id))stationMeta.set(d.id,{id:d.id,name:d.name,hub:d.hub,rawIds:new Set(),memberNames:new Set(),connections:new Set()});const m=stationMeta.get(d.id);m.rawIds.add(s.id);m.memberNames.add(String(s.name||s.id))}
  for(const s of data.stations||[]){const a=rawToLogical.get(s.id),m=stationMeta.get(a);for(const rr of s.connections||[]){const b=rawToLogical.get(rr);if(b&&b!==a)m.connections.add(b)}}
  function ensure(rawId,name){if(rawToLogical.has(rawId))return rawToLogical.get(rawId);const d=logicalFor(rawStation.get(rawId)||{id:rawId,name:name||rawId});rawToLogical.set(rawId,d.id);if(!stationMeta.has(d.id))stationMeta.set(d.id,{id:d.id,name:d.name,hub:d.hub,rawIds:new Set([rawId]),memberNames:new Set([name||rawId]),connections:new Set()});return d.id}
  const occurrences=new Map(),services=[];
  for(const r of data.routes||[]){if(r.hidden||!Array.isArray(r.stations)||r.stations.length<2)continue;const mode=modeOf(r.type);if(!mode)continue;const nodes=[];for(const st of r.stations){if(!st?.id||!Number.isFinite(+st.x)||!Number.isFinite(+st.z))continue;const id=ensure(st.id,st.name);if(nodes.at(-1)!==id)nodes.push(id);if(!occurrences.has(id))occurrences.set(id,[]);occurrences.get(id).push({x:+st.x,y:+st.z})}if(nodes.length>=2)services.push({id:r.id,label:String(r.name??r.routeNumber??r.number??r.id).trim(),mode,color:Number(r.color??0),nodes})}
  const original=new Map();for(const[id,pts]of occurrences)original.set(id,{x:pts.reduce((s,p)=>s+p.x,0)/pts.length,y:pts.reduce((s,p)=>s+p.y,0)/pts.length});
  const parent=services.map((_,i)=>i),find=i=>parent[i]===i?i:(parent[i]=find(parent[i])),union=(a,b)=>{a=find(a);b=find(b);if(a!==b)parent[b]=a};
  const overlap=(a,b)=>{const A=new Set(a),B=new Set(b);let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(1,Math.min(A.size,B.size))};
  for(let i=0;i<services.length;i++)for(let j=i+1;j<services.length;j++){const a=services[i],b=services[j];if(a.mode!==b.mode)continue;if(norm(a.label)===norm(b.label)||(a.color===b.color&&overlap(a.nodes,b.nodes)>=.65))union(i,j)}
  const clusters=new Map();services.forEach((s,i)=>{const k=find(i);if(!clusters.has(k))clusters.set(k,[]);clusters.get(k).push(s)});
  const groups=[];let gi=0;for(const list of clusters.values()){const mode=list[0].mode,cc=new Map(),lc=new Map();for(const s of list){cc.set(s.color,(cc.get(s.color)||0)+1);lc.set(s.label,(lc.get(s.label)||0)+1)}const color=[...cc].sort((a,b)=>b[1]-a[1])[0][0],label=[...lc].sort((a,b)=>b[1]-a[1])[0][0];groups.push({id:`${mode}|${color}|${gi++}`,label,mode,color,services:list,nodes:new Set(),edges:new Set(),selectiveStops:new Set()})}
  groups.sort((a,b)=>modeOrder(a.mode)-modeOrder(b.mode)||a.label.localeCompare(b.label,undefined,{numeric:true}));
  const rank=new Map(groups.map((g,i)=>[g.id,i])),groupById=new Map(groups.map(g=>[g.id,g]));
  const physical=new Map();
  for(const g of groups)for(const s of g.services){for(const n of s.nodes)g.nodes.add(n);for(let i=1;i<s.nodes.length;i++){const k=pairKey(s.nodes[i-1],s.nodes[i]);g.edges.add(k);if(!physical.has(k)){const[a,b]=k.split('|');physical.set(k,{key:k,a,b,routes:new Set()})}physical.get(k).routes.add(g.id)}}
  const physAdj=new Map();for(const e of physical.values()){if(!physAdj.has(e.a))physAdj.set(e.a,[]);if(!physAdj.has(e.b))physAdj.set(e.b,[]);physAdj.get(e.a).push(e);physAdj.get(e.b).push(e)}
  function alternatePath(a,b,excludeKey){const A=original.get(a),B=original.get(b);if(!A||!B)return null;const direct=Math.max(1,dist(A,B)),stack=[{n:a,path:[a],len:0}],seen=new Map([[a,0]]);let best=null;while(stack.length){const cur=stack.pop();if(cur.path.length-1>=CFG.shortcutHops)continue;for(const e of physAdj.get(cur.n)||[]){if(e.key===excludeKey)continue;const nx=e.a===cur.n?e.b:e.a;if(cur.path.includes(nx))continue;const P=original.get(cur.n),Q=original.get(nx);if(!P||!Q)continue;const len=cur.len+dist(P,Q);if(len>direct*1.7)continue;const path=[...cur.path,nx];if(nx===b&&path.length>=3){const mids=path.slice(1,-1).map(x=>original.get(x)).filter(Boolean),maxPerp=mids.length?Math.max(...mids.map(p=>pointSegDistance(p,A,B))):Infinity;if(len/direct<=CFG.shortcutRatio&&maxPerp<=direct*CFG.shortcutPerp){const score=len/direct+maxPerp/direct;if(!best||score<best.score)best={path,score}}}else if(len<(seen.get(nx)??Infinity)*1.05){seen.set(nx,len);stack.push({n:nx,path,len})}}}return best?.path||null}
  for(const g of groups){const expanded=new Set(),stopCounts=new Map();for(const s of g.services)for(const n of new Set(s.nodes))stopCounts.set(n,(stopCounts.get(n)||0)+1);for(const k of g.edges){const[a,b]=k.split('|'),alt=alternatePath(a,b,k);if(alt){for(let i=1;i<alt.length;i++)expanded.add(pairKey(alt[i-1],alt[i]));for(const mid of alt.slice(1,-1))if((stopCounts.get(mid)||0)<g.services.length)g.selectiveStops.add(mid)}else expanded.add(k)}g.edges=expanded;g.nodes=new Set([...expanded].flatMap(k=>k.split('|')))}
  const edges=new Map(),nodeGroups=new Map(),endpoints=new Set();for(const g of groups){for(const n of g.nodes){if(!nodeGroups.has(n))nodeGroups.set(n,new Set());nodeGroups.get(n).add(g.id)}for(const s of g.services){if(s.nodes.length){endpoints.add(s.nodes[0]);endpoints.add(s.nodes.at(-1))}}for(const k of g.edges){let e=edges.get(k);if(!e){const[a,b]=k.split('|');e={key:k,a,b,routes:new Set()};edges.set(k,e)}e.routes.add(g.id)}}
  const lengths=[];for(const e of edges.values()){const a=original.get(e.a),b=original.get(e.b);if(a&&b)lengths.push(dist(a,b))}const scale=CFG.spacing/Math.max(1,median(lengths)),vals=[...original.values()],cx=vals.reduce((s,p)=>s+p.x,0)/Math.max(1,vals.length),cy=vals.reduce((s,p)=>s+p.y,0)/Math.max(1,vals.length);const geo=new Map();for(const[id,p]of original)geo.set(id,{x:(p.x-cx)*scale,y:(p.y-cy)*scale});
  const byName=new Map([...stationMeta.values()].map(m=>[norm(m.name),m.id]));
  return{stationMeta,groups,groupById,rank,edges,nodeGroups,endpoints,original,geo,byName};
}
function buildAdj(model,routeFilter=null){const adj=new Map();for(const e of model.edges.values()){if(routeFilter&&![...e.routes].some(routeFilter))continue;if(!adj.has(e.a))adj.set(e.a,[]);if(!adj.has(e.b))adj.set(e.b,[]);adj.get(e.a).push(e);adj.get(e.b).push(e)}return adj}
function canonicalEdgeDir(edge){const A=state.model.geo.get(edge.a),B=state.model.geo.get(edge.b);if(!A||!B)return[edge.a,edge.b];if(A.y<B.y-1)return[edge.a,edge.b];if(B.y<A.y-1)return[edge.b,edge.a];return A.x<=B.x?[edge.a,edge.b]:[edge.b,edge.a]}
function routeLaneOrder(ids){return[...ids].sort((a,b)=>(state.model.rank.get(a)??999)-(state.model.rank.get(b)??999))}
function edgeLaneOffset(edge,id){const ids=routeLaneOrder([...edge.routes].filter(r=>state.visible.has(state.model.groupById.get(r)?.mode)));if(ids.length<=1)return 0;return(ids.indexOf(id)-(ids.length-1)/2)*CFG.laneGap}
function preprocessPositions(model){const pos=new Map([...model.geo].map(([k,p])=>[k,{...p}])),adj=buildAdj(model);for(let pass=0;pass<2;pass++)for(const[n,links]of adj){if(links.length!==2)continue;const a=links[0].a===n?links[0].b:links[0].a,b=links[1].a===n?links[1].b:links[1].a,A=pos.get(a),P=pos.get(n),B=pos.get(b);if(!A||!P||!B)continue;const base=Math.max(1,dist(A,B));if(pointSegDistance(P,A,B)<=base*CFG.straightTol)pos.set(n,projectToSeg(P,A,B))}return pos}
function createOverlay(){const w=state.wrapper;w.style.position=w.style.position||'relative';const ov=document.createElement('div');ov.id='folityn-v62-overlay';ov.style.cssText='position:absolute;inset:0;z-index:30;overflow:hidden;cursor:grab;user-select:none;touch-action:none;';const svg=svgEl('svg',{width:'100%',height:'100%',xmlns:NS});ov.appendChild(svg);w.appendChild(ov);const bg=svgEl('rect',{x:-100000,y:-100000,width:200000,height:200000}),root=svgEl('g'),routes=svgEl('g'),stops=svgEl('g'),labels=svgEl('g'),hits=svgEl('g');root.append(routes,stops,labels,hits);svg.append(bg,root);state.overlay=ov;state.svg=svg;state.layers={bg,root,routes,stops,labels,hits}}
function bounds(){const v=[...state.model.pos.values()];const minX=Math.min(...v.map(p=>p.x))-CFG.pad,maxX=Math.max(...v.map(p=>p.x))+CFG.pad,minY=Math.min(...v.map(p=>p.y))-CFG.pad,maxY=Math.max(...v.map(p=>p.y))+CFG.pad;return{x:minX,y:minY,w:maxX-minX,h:maxY-minY}}
function fit(){state.fitView=bounds();state.view={...state.fitView};state.svg.setAttribute('viewBox',`${state.view.x} ${state.view.y} ${state.view.w} ${state.view.h}`)}
function applyView(){const v=state.view;state.svg.setAttribute('viewBox',`${v.x} ${v.y} ${v.w} ${v.h}`)}
function drawPath(id,points,width){const r=state.model.groupById.get(id),selected=state.selectedRoute===id,dim=state.selectedRoute&&!selected,d=roundedPath(points);const p=svgEl('path',{d,fill:'none',stroke:colorHex(r.color),'stroke-width':width+(selected?2:0),'stroke-linecap':'round','stroke-linejoin':'round',opacity:dim?.14:1});state.layers.routes.appendChild(p);const hit=svgEl('path',{d,fill:'none',stroke:'transparent','stroke-width':Math.max(16,width+10),'pointer-events':'stroke','data-route-hit':id});hit.style.cursor='pointer';hit.onclick=e=>{e.stopPropagation();state.selectedRoute=id;showRoutePanel(id);render()};state.layers.hits.appendChild(hit)}
function drawTrainLayer(){const central=state.model.byName.get(norm('Folityn Centralny')),trainGroups=state.model.groups.filter(g=>g.mode==='rail'||g.mode==='high_speed'),servingCentral=trainGroups.filter(g=>central&&g.nodes.has(central)),throatRoutes=routeLaneOrder(servingCentral.map(g=>g.id)),C=central?state.model.pos.get(central):null,top=C?{x:C.x,y:C.y-CFG.throatHalf}:null,bottom=C?{x:C.x,y:C.y+CFG.throatHalf}:null;if(C&&throatRoutes.length)for(let i=0;i<throatRoutes.length;i++){const id=throatRoutes[i],off=(i-(throatRoutes.length-1)/2)*CFG.laneGap;drawPath(id,[{x:top.x+off,y:top.y},{x:C.x+off,y:C.y},{x:bottom.x+off,y:bottom.y}],state.model.groupById.get(id).mode==='high_speed'?4.8:4.4)}for(const g of trainGroups){if(!state.visible.has(g.mode))continue;const adj=new Map();for(const k of g.edges){const e=state.model.edges.get(k);if(!e)continue;if(!adj.has(e.a))adj.set(e.a,[]);if(!adj.has(e.b))adj.set(e.b,[]);adj.get(e.a).push(e);adj.get(e.b).push(e)}const starts=[...adj.keys()].filter(n=>(adj.get(n)?.length||0)!==2),visited=new Set();const walk=(s,first)=>{const nodes=[s];let cur=s,e=first;while(e&&!visited.has(e.key)){visited.add(e.key);cur=e.a===cur?e.b:e.a;nodes.push(cur);if((adj.get(cur)?.length||0)!==2)break;e=adj.get(cur).find(x=>!visited.has(x.key))}if(nodes.length<2)return;let pts=[];for(const n of nodes){if(n===central&&C){pts.push({...top},{...C},{...bottom})}else{const p=state.model.pos.get(n);if(p)pts.push({...p})}}if(C&&g.nodes.has(central))pts=pts.filter(p=>!(p.y>=top.y-1&&p.y<=bottom.y+1&&Math.abs(p.x-C.x)<4));if(pts.length<2)return;const snapped=[pts[0]];for(let i=1;i<pts.length;i++)snapped.push(snapDir(snapped.at(-1),pts[i]));drawPath(g.id,snapped,g.mode==='high_speed'?4.8:4.4)};for(const s of starts)for(const e of adj.get(s)||[])if(!visited.has(e.key))walk(s,e);for(const[s,list]of adj)for(const e of list)if(!visited.has(e.key))walk(s,e)}}
function drawLightRailLayer(){for(const e of state.model.edges.values()){const ids=routeLaneOrder([...e.routes].filter(id=>state.model.groupById.get(id)?.mode==='light_rail'&&state.visible.has('light_rail')));if(!ids.length)continue;const[ca,cb]=canonicalEdgeDir(e),A=state.model.pos.get(ca),B=state.model.pos.get(cb);if(!A||!B)continue;const base=[A,snapDir(A,B)];for(const id of ids)drawPath(id,offsetPolyline(base,edgeLaneOffset(e,id)),4.5)}}
function stationAngle(node){const adj=buildAdj(state.model),links=adj.get(node)||[],p=state.model.pos.get(node);if(!p||!links.length)return 0;let sx=0,sy=0;for(const e of links){const o=e.a===node?e.b:e.a,q=state.model.pos.get(o);if(!q)continue;const a=Math.atan2(q.y-p.y,q.x-p.x);sx+=Math.cos(2*a);sy+=Math.sin(2*a)}return.5*Math.atan2(sy,sx)}
function drawHubIcon(group,p,size){const fg=state.dark?'#eef3fb':'#172033',bg=state.dark?'#0f1828':'#fff';group.appendChild(svgEl('circle',{cx:p.x,cy:p.y,r:size,fill:bg,stroke:fg,'stroke-width':3}));group.appendChild(svgEl('rect',{x:p.x-size*.55,y:p.y-size*.42,width:size*.42,height:size*.64,rx:2.5,fill:'none',stroke:fg,'stroke-width':2}));group.appendChild(svgEl('rect',{x:p.x+size*.02,y:p.y-size*.34,width:size*.48,height:size*.48,rx:2.5,fill:'none',stroke:fg,'stroke-width':2}))}
function drawStops(){const sg=state.layers.stops,lg=state.layers.labels;sg.textContent='';lg.textContent='';const fg=state.dark?'#eef3fb':'#172033',bg=state.dark?'#0f1828':'#fff';for(const[node,idsSet]of state.model.nodeGroups){const ids=[...idsSet].filter(id=>state.visible.has(state.model.groupById.get(id)?.mode));if(!ids.length)continue;const p=state.model.pos.get(node),m=state.model.stationMeta.get(node);if(!p||!m)continue;const central=m.hub==='central',hub=m.hub==='wity'||m.hub==='jamnikowsko',major=central||hub||ids.length>=3||m.connections.size>0;if(central)drawHubIcon(sg,p,22);else if(hub)drawHubIcon(sg,p,14);else if(major){const ang=stationAngle(node)*180/Math.PI,w=34+Math.min(20,ids.length*3),h=14;sg.appendChild(svgEl('rect',{x:p.x-w/2,y:p.y-h/2,width:w,height:h,rx:7,fill:bg,stroke:fg,'stroke-width':2,transform:`rotate(${ang} ${p.x} ${p.y})`}))}else sg.appendChild(svgEl('circle',{cx:p.x,cy:p.y,r:4.5,fill:bg,stroke:fg,'stroke-width':1.8}));const selective=[...idsSet].some(id=>state.model.groupById.get(id)?.selectiveStops.has(node));if(selective)sg.appendChild(svgEl('path',{d:`M ${p.x+6} ${p.y-5} L ${p.x+6} ${p.y+5}`,stroke:fg,'stroke-width':2.2,'stroke-linecap':'round'}));const hit=svgEl('circle',{cx:p.x,cy:p.y,r:central?30:hub?22:16,fill:'transparent','pointer-events':'all','data-station-hit':node});hit.style.cursor='pointer';hit.onclick=e=>{e.stopPropagation();showStationPanel(node)};state.layers.hits.appendChild(hit);const show=state.labels==='all'||(state.labels==='key'&&(major||state.model.endpoints.has(node)));if(show){const t=svgEl('text',{x:p.x+10,y:p.y-10,fill:fg,'font-size':central?14:major?11.5:10.5,'font-family':'Arial,sans-serif','paint-order':'stroke',stroke:bg,'stroke-width':3});t.textContent=m.name;lg.appendChild(t)}}}
function render(){state.layers.bg.setAttribute('fill',state.dark?'#0f1828':'#f7f8fa');state.layers.routes.textContent='';state.layers.hits.textContent='';drawTrainLayer();drawLightRailLayer();drawStops()}
function panelBase(title){if(!state.panel){const p=document.createElement('div');p.style.cssText='position:fixed;right:18px;top:64px;z-index:100002;width:320px;max-height:calc(100vh - 90px);overflow:auto;background:rgba(12,18,30,.98);color:#eef3fb;border:1px solid #ffffff22;border-radius:14px;padding:14px;box-shadow:0 12px 36px #0009;font:13px/1.4 Arial,sans-serif;';document.body.appendChild(p);state.panel=p}state.panel.style.display='block';state.panel.innerHTML=`<button id="fol-x" style="float:right;border:0;background:#25324a;color:#fff;border-radius:7px;padding:3px 7px;cursor:pointer">×</button><div style="font-size:17px;font-weight:750;margin:0 34px 10px 0">${title}</div><div id="fol-body"></div>`;state.panel.querySelector('#fol-x').onclick=()=>state.panel.style.display='none';return state.panel.querySelector('#fol-body')}
function showStationPanel(node){const m=state.model.stationMeta.get(node),raw=state.model.original.get(node);if(!m)return;const body=panelBase(m.name),routes=[...(state.model.nodeGroups.get(node)||[])].map(id=>state.model.groupById.get(id)).filter(Boolean);body.innerHTML=`${m.memberNames.size>1?`<div style="opacity:.65;font-size:11px;text-transform:uppercase">Grouped MTR stops</div>${[...m.memberNames].map(x=>`<div>• ${x}</div>`).join('')}`:''}${raw?`<div style="opacity:.65;margin:8px 0">Minecraft X ${Math.round(raw.x)} · Z ${Math.round(raw.y)}</div>`:''}<div style="opacity:.65;font-size:11px;text-transform:uppercase;margin-top:9px">Services</div>${routes.map(r=>`<div style="border-left:5px solid ${colorHex(r.color)};padding:3px 7px;margin:4px 0;background:#ffffff0d">${r.label} · ${modeLabel(r.mode)}</div>`).join('')}`}
function showRoutePanel(id){const r=state.model.groupById.get(id);if(!r)return;const body=panelBase(r.label);body.innerHTML=`<div style="opacity:.7">${modeLabel(r.mode)}</div><div style="margin-top:8px">${[...r.nodes].map(n=>state.model.stationMeta.get(n)?.name||n).join(' → ')}</div>`}
function buildControls(){const box=document.createElement('div');box.style.cssText='position:fixed;left:14px;bottom:14px;z-index:99999;background:rgba(12,18,30,.94);color:#fff;padding:12px 13px;border-radius:12px;font:13px/1.35 Arial,sans-serif;box-shadow:0 6px 24px #0008;min-width:215px;';box.innerHTML='<div style="font-weight:700;font-size:14px">Folityn schematic v6.2</div><div style="opacity:.7;font-size:11px;margin:2px 0 9px">train corridor model · Centralny throat</div>';for(const[m,l]of[['light_rail','Light Rail'],['rail','Rail'],['high_speed','High Speed']]){const row=document.createElement('label');row.style.cssText='display:block;margin:5px 0';const cb=document.createElement('input');cb.type='checkbox';cb.checked=state.visible.has(m);cb.style.marginRight='7px';cb.onchange=()=>{cb.checked?state.visible.add(m):state.visible.delete(m);localStorage.setItem(KEY+'modes',JSON.stringify([...state.visible]));render()};row.append(cb,document.createTextNode(l));box.appendChild(row)}const fitB=document.createElement('button');fitB.textContent='Fit';fitB.style.cssText='width:100%;margin-top:6px;padding:6px;border:0;border-radius:7px;background:#25324a;color:#fff';fitB.onclick=fit;box.appendChild(fitB);document.body.appendChild(box)}
function interaction(){const ov=state.overlay;ov.addEventListener('mousedown',e=>{if(e.button!==0||e.target?.dataset?.stationHit||e.target?.dataset?.routeHit)return;state.drag={x:e.clientX,y:e.clientY,view:{...state.view}};ov.style.cursor='grabbing'});window.addEventListener('mousemove',e=>{if(!state.drag)return;if(!(e.buttons&1)){state.drag=null;ov.style.cursor='grab';return}const r=ov.getBoundingClientRect(),dx=(e.clientX-state.drag.x)*state.drag.view.w/r.width,dy=(e.clientY-state.drag.y)*state.drag.view.h/r.height;state.view={...state.drag.view,x:state.drag.view.x-dx,y:state.drag.view.y-dy};applyView()});window.addEventListener('mouseup',()=>{state.drag=null;ov.style.cursor='grab'});ov.addEventListener('wheel',e=>{e.preventDefault();const r=ov.getBoundingClientRect(),mx=(e.clientX-r.left)/r.width,my=(e.clientY-r.top)/r.height,f=Math.exp(e.deltaY*.0012),o=state.view,nw=clamp(o.w*f,state.fitView.w*.07,state.fitView.w*8),nh=nw*o.h/o.w;state.view={x:o.x+mx*(o.w-nw),y:o.y+my*(o.h-nh),w:nw,h:nh};applyView()},{passive:false});ov.ondblclick=fit}
async function init(){try{state.wrapper=await waitForMap();state.model=buildModel(await loadNetwork());state.model.pos=preprocessPositions(state.model);createOverlay();fit();render();buildControls();interaction()}catch(e){console.error('[Folityn v6.2]',e)}}
init();
})();