// ==UserScript==
// @name         MTR Map Tools - Folityn Shared Train Corridors v10
// @namespace    https://github.com/peachemce/mtr-map-tools
// @version      10.0.0
// @description  Original MTR map for non-train modes; Centralny Rail/High Speed rendered from one shared physical corridor graph.
// @match        http://localhost:8888/*
// @run-at       document-start
// @grant        none
// @sandbox      raw
// @updateURL    https://raw.githubusercontent.com/peachemce/mtr-map-tools/main/connector-reroll.user.js
// @downloadURL  https://raw.githubusercontent.com/peachemce/mtr-map-tools/main/connector-reroll.user.js
// ==/UserScript==
(() => {
'use strict';
const TARGET=/\/mtr\/api\/map\/stations-and-routes(?:\?|$)/, TYPES=new Set(['train_normal','train_high_speed']), CENTRAL='folityn centralny';
const KEY='folityn-v10-', ON=localStorage.getItem(KEY+'on')!=='0', norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase();
const rs=r=>Array.isArray(r?.stations)?r.stations:[], id=s=>String(s?.id??''), p=s=>Number.isFinite(+s?.x)&&Number.isFinite(+s?.z)?{x:+s.x,z:+s.z}:null;
const med=a=>{if(!a.length)return 0;let b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2}, d=(a,b)=>Math.hypot(b.x-a.x,b.z-a.z), hex=n=>'#'+(Number(n)>>>0).toString(16).padStart(6,'0').slice(-6);
const base=n=>norm(n).replace(/\s+[12]$/,'').replace(/([a-z])([12])$/,'$1'), sk=r=>`${r.type}|${Number(r.color)||0}|${base(r.name||'')}`;
let MODEL=null,NATIVE=new Map();
const groupName=n=>{n=norm(n);if(n===CENTRAL)return CENTRAL;if(n==='folityn jamnikowsko'||n==='jamnikowsko pkm')return'folityn jamnikowsko';if(n==='folityn wity'||n==='wity pkm')return'wity';return'name:'+n};
function alt(a,c,adj,pts){let A=pts.get(a),C=pts.get(c);if(!A||!C)return null;let direct=Math.max(1,d(A,C)),best=null,seen=new Set([a]);const walk=(n,path,len)=>{if(path.length>5)return;if(n===c){if(path.length<=2)return;let vx=C.x-A.x,vz=C.z-A.z,vv=vx*vx+vz*vz,perp=0;for(let k of path.slice(1,-1)){let q=pts.get(k),t=vv?((q.x-A.x)*vx+(q.z-A.z)*vz)/vv:0;perp=Math.max(perp,d(q,{x:A.x+vx*t,z:A.z+vz*t}))}if(len<=direct*1.18&&perp<=Math.max(90,direct*.12)&&(!best||len<best.len))best={path:[...path],len};return}for(let x of adj.get(n)||[]){if((n===a&&x===c)||seen.has(x))continue;let P=pts.get(n),Q=pts.get(x),nl=len+d(P,Q);if(nl>direct*1.22)continue;seen.add(x);path.push(x);walk(x,path,nl);path.pop();seen.delete(x)}};walk(a,[a],0);return best?.path||null}
function build(src){let top=new Map((src.stations||[]).map(s=>[String(s.id),s])),sel=(src.routes||[]).filter(r=>TYPES.has(r.type)&&rs(r).some(s=>norm(top.get(id(s))?.name)===CENTRAL));if(!sel.length)return null;
 let occ=new Map;for(let r of sel)for(let s of rs(r)){let k=id(s),q=p(s);if(!k||!q)continue;if(!occ.has(k))occ.set(k,[]);occ.get(k).push(q)}
 let raw2log=new Map,members=new Map,names=new Map;for(let k of occ.keys()){let disp=String(top.get(k)?.name??k),g=groupName(disp);raw2log.set(k,g);if(!members.has(g))members.set(g,[]);members.get(g).push(k);names.set(g,g.startsWith('name:')?disp:g===CENTRAL?'Folityn Centralny':g==='wity'?'Wity':'Folityn Jamnikowsko')}
 let pts=new Map;for(let[g,ids]of members){let q=ids.flatMap(k=>occ.get(k)||[]);pts.set(g,{x:med(q.map(v=>v.x)),z:med(q.map(v=>v.z))})}let C=pts.get(CENTRAL);if(!C)return null;
 let vars=sel.map(r=>{let q=[];for(let s of rs(r)){let g=raw2log.get(id(s));if(g&&q.at(-1)!==g)q.push(g)}return{r,key:sk(r),orig:q,seq:[...q]}}).filter(v=>v.seq.length>1);
 let adj=new Map([...pts.keys()].map(k=>[k,new Set]));for(let v of vars)for(let i=1;i<v.seq.length;i++){let a=v.seq[i-1],b=v.seq[i];adj.get(a)?.add(b);adj.get(b)?.add(a)}
 for(let v of vars){let out=[v.seq[0]];for(let i=1;i<v.seq.length;i++){let a=v.seq[i-1],c=v.seq[i],q=alt(a,c,adj,pts);out.push(...(q&&q.length>2?q.slice(1):[c]))}v.seq=out.filter((x,i,a)=>!i||x!==a[i-1])}
 let sv=new Map;for(let v of vars){if(!sv.has(v.key))sv.set(v.key,{name:base(v.r.name||''),color:+v.r.color||0,type:v.r.type,vars:[]});sv.get(v.key).vars.push(v)}let order=[...sv.keys()].sort((a,b)=>sv.get(a).color-sv.get(b).color||sv.get(a).name.localeCompare(sv.get(b).name)),lane=new Map(order.map((k,i)=>[k,i-(order.length-1)/2]));
 let ek=(a,b)=>a<b?`${a}__${b}`:`${b}__${a}`,rawEdges=new Map,add=(map,a,b,k)=>{let e=ek(a,b);if(!map.has(e))map.set(e,{a:a<b?a:b,b:a<b?b:a,s:new Set});map.get(e).s.add(k)};for(let v of vars)for(let i=1;i<v.seq.length;i++)add(rawEdges,v.seq[i-1],v.seq[i],v.key);
 let lens=[];for(let e of rawEdges.values())if(pts.get(e.a)&&pts.get(e.b))lens.push(d(pts.get(e.a),pts.get(e.b)));let typical=Math.max(240,med(lens.filter(x=>x>30))||600),half=Math.max(160,Math.min(420,typical*.38));pts.set('__N',{x:C.x,z:C.z+half});pts.set('__S',{x:C.x,z:C.z-half});
 let side=n=>{let q=pts.get(n),dz=q.z-C.z;if(Math.abs(dz)>typical*.08)return dz>0?'N':'S';return q.x>=C.x?'N':'S'},edges=new Map;for(let e of rawEdges.values())if(e.a!==CENTRAL&&e.b!==CENTRAL)for(let k of e.s)add(edges,e.a,e.b,k);
 let use=new Map([...sv.keys()].map(k=>[k,{N:false,S:false,through:false}]));for(let v of vars){let i=v.seq.indexOf(CENTRAL);if(i<0)continue;let a=i?v.seq[i-1]:null,b=i<v.seq.length-1?v.seq[i+1]:null;if(a){let s=side(a);use.get(v.key)[s]=true;add(edges,a,'__'+s,v.key)}if(b){let s=side(b);use.get(v.key)[s]=true;add(edges,'__'+s,b,v.key)}if(a&&b)use.get(v.key).through=true}for(let[k,u]of use){if(u.through||(u.N&&u.S)){add(edges,'__N',CENTRAL,k);add(edges,CENTRAL,'__S',k)}else if(u.N)add(edges,'__N',CENTRAL,k);else if(u.S)add(edges,CENTRAL,'__S',k)}
 return{ids:new Set(sel.map(r=>String(r.id))),pts,names,sv,lane,edges,central:CENTRAL};}
function nativePts(data){let top=new Map((data.stations||[]).map(s=>[String(s.id),s])),o=new Map;for(let r of data.routes||[])for(let s of rs(r)){let q=p(s),k=id(s);if(!q||!k)continue;if(!o.has(k))o.set(k,[]);o.get(k).push(q)}let by=new Map;for(let[k,ps]of o){let n=norm(top.get(k)?.name);if(!n)continue;if(!by.has(n))by.set(n,[]);by.get(n).push({x:med(ps.map(q=>q.x)),z:med(ps.map(q=>q.z))})}let out=new Map;for(let[n,ps]of by)out.set(n,{x:med(ps.map(q=>q.x)),z:med(ps.map(q=>q.z))});return out}
function transform(env){if(!ON||!env||typeof env!=='object')return env;let src=env.data&&typeof env.data==='object'?env.data:env;if(!Array.isArray(src.routes)||!Array.isArray(src.stations))return env;MODEL=build(src);let out=typeof structuredClone==='function'?structuredClone(env):JSON.parse(JSON.stringify(env)),data=out.data&&typeof out.data==='object'?out.data:out;if(MODEL)data.routes=(data.routes||[]).filter(r=>!MODEL.ids.has(String(r.id)));NATIVE=nativePts(data);return out}
const tx=t=>{try{return JSON.stringify(transform(JSON.parse(t)))}catch(e){console.warn('[v10]',e);return t}},nf=window.fetch.bind(window);window.fetch=async function(i,o){let u=typeof i==='string'?i:i?.url||'',r=await nf(i,o);if(!TARGET.test(u))return r;try{return new Response(tx(await r.clone().text()),{status:r.status,statusText:r.statusText,headers:r.headers})}catch{return r}};
try{let p=XMLHttpRequest.prototype,op=p.open,tg=Object.getOwnPropertyDescriptor(p,'responseText')?.get,rg=Object.getOwnPropertyDescriptor(p,'response')?.get,c=new WeakMap;p.open=function(m,u,...x){this.__v10=TARGET.test(String(u));c.delete(this);return op.call(this,m,u,...x)};if(tg)Object.defineProperty(p,'responseText',{configurable:true,get(){let r=tg.call(this);if(!this.__v10||this.readyState!==4||typeof r!=='string')return r;let x=c.get(this);if(!x){x={t:tx(r)};c.set(this,x)}return x.t}});if(rg)Object.defineProperty(p,'response',{configurable:true,get(){let r=rg.call(this);if(!this.__v10||this.readyState!==4)return r;let x=c.get(this)||{};if(this.responseType==='json'&&r&&typeof r==='object'){if(!x.j){x.j=transform(r);c.set(this,x)}return x.j}if((this.responseType===''||this.responseType==='text')&&typeof r==='string'){if(!x.t){x.t=tx(r);c.set(this,x)}return x.t}return r}})}catch(e){console.warn('[v10 xhr]',e)}
function labelXY(el){let a=[...(el.style.transform||'').matchAll(/translate\(\s*(-?[\d.]+)px\s*,\s*(-?[\d.]+)px\s*\)/g)],m=a.at(-1);return m?{x:+m[1],y:+m[2]}:null}
function view(){let a=[];for(let el of document.querySelectorAll('app-map .label[aria-label]')){let q=labelXY(el),w=NATIVE.get(norm(el.getAttribute('aria-label')));if(q&&w)a.push({q,w})}if(a.length<2)return null;let s=[];for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){let dx=a[j].w.x-a[i].w.x,dz=a[j].w.z-a[i].w.z;if(Math.abs(dx)>120)s.push((a[j].q.x-a[i].q.x)/dx);if(Math.abs(dz)>120)s.push((a[j].q.y-a[i].q.y)/(-dz))}s=s.filter(x=>Number.isFinite(x)&&Math.abs(x)>.0001);if(!s.length)return null;let k=med(s);return{k,tx:med(a.map(x=>x.q.x-k*x.w.x)),ty:med(a.map(x=>x.q.y+k*x.w.z))}}
function geom(a,b){let dx=b.x-a.x,dz=b.z-a.z,x=Math.abs(dx),z=Math.abs(dz),eps=Math.max(30,Math.min(x,z)*.16);if(x<eps||z<eps||Math.abs(x-z)<Math.max(35,Math.max(x,z)*.12))return[a,b];return x>z?[a,{x:a.x+Math.sign(dx)*(x-z),z:a.z},b]:[a,{x:a.x,z:a.z+Math.sign(dz)*(z-x)},b]}
function off(P,o){if(Math.abs(o)<.01)return P;let seg=[];for(let i=0;i<P.length-1;i++){let a=P[i],b=P[i+1],dx=b.x-a.x,dz=b.z-a.z,l=Math.hypot(dx,dz)||1;seg.push({x:-dz/l,z:dx/l})}return P.map((p,i)=>{let n=i?i===P.length-1?seg.at(-1):{x:seg[i-1].x+seg[i].x,z:seg[i-1].z+seg[i].z}:seg[0],l=Math.hypot(n.x,n.z)||1;return{x:p.x+n.x/l*o,z:p.z+n.z/l*o}})}
function dpath(P){let q=`M ${P[0].x} ${P[0].y}`;if(P.length===2)return q+` L ${P[1].x} ${P[1].y}`;for(let i=1;i<P.length-1;i++){let p=P[i],n=P[i+1];q+=` Q ${p.x} ${p.y} ${(p.x+n.x)/2} ${(p.y+n.y)/2}`}return q+` L ${P.at(-1).x} ${P.at(-1).y}`}
function install(){if(!document.body)return setTimeout(install,50);let ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.id='f10';svg.style='position:fixed;inset:0;z-index:18;pointer-events:none';document.body.appendChild(svg);let st=document.createElement('style');st.textContent='#f10 path{fill:none;stroke-linecap:round;stroke-linejoin:round}.f10s{fill:#0b1220;stroke:#eef4ff;stroke-width:2}.f10h{fill:#0b1220;stroke:#eef4ff;stroke-width:3}.f10t{font:600 12px Arial;fill:#eef4ff;paint-order:stroke;stroke:#0b1220;stroke-width:3px}#f10p{position:fixed;left:14px;bottom:14px;z-index:99999;background:#0b1220ee;color:#fff;padding:8px 10px;border-radius:9px;font:12px Arial}';document.head.appendChild(st);let box=document.createElement('div');box.id='f10p';box.innerHTML='<b>Shared train corridors v10</b><br><span style="opacity:.65">Centralny routes only</span>';document.body.appendChild(box);let sig='';function draw(){requestAnimationFrame(draw);if(!MODEL)return;let V=view();if(!V)return;let z=[V.k.toFixed(5),V.tx.toFixed(1),V.ty.toFixed(1),MODEL.edges.size].join('|');if(z===sig)return;sig=z;svg.replaceChildren();let S=q=>({x:V.tx+V.k*q.x,y:V.ty-V.k*q.z});for(let e of MODEL.edges.values()){let A=MODEL.pts.get(e.a),B=MODEL.pts.get(e.b);if(!A||!B)continue;for(let k of [...e.s].sort((a,b)=>(MODEL.lane.get(a)||0)-(MODEL.lane.get(b)||0))){let svc=MODEL.sv.get(k),o=(MODEL.lane.get(k)||0)*4.5/Math.max(.25,Math.abs(V.k)),P=off(geom(A,B),o).map(S),path=document.createElementNS(ns,'path');path.setAttribute('d',dpath(P));path.setAttribute('stroke',hex(svc.color));path.setAttribute('stroke-width',svc.type==='train_high_speed'?'3.6':'3');svg.appendChild(path)}}let nodes=new Set;for(let e of MODEL.edges.values()){nodes.add(e.a);nodes.add(e.b)}for(let n of nodes){if(n.startsWith('__'))continue;let q=MODEL.pts.get(n),s=S(q),c=document.createElementNS(ns,n===MODEL.central?'rect':'circle');if(n===MODEL.central){c.setAttribute('x',s.x-18);c.setAttribute('y',s.y-12);c.setAttribute('width',36);c.setAttribute('height',24);c.setAttribute('rx',10);c.setAttribute('class','f10h')}else{c.setAttribute('cx',s.x);c.setAttribute('cy',s.y);c.setAttribute('r',5);c.setAttribute('class','f10s')}svg.appendChild(c);let name=MODEL.names.get(n);if(name){let t=document.createElementNS(ns,'text');t.setAttribute('x',s.x+8);t.setAttribute('y',s.y-7);t.setAttribute('class','f10t');t.textContent=name;svg.appendChild(t)}}}draw()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
